### ISSUE TITLE
Database: Investigate Database type and hosted options

### ISSUE THREAD

**Issue by Alesvoy** [masiddee/nextjs-soccer-manager#1]
# Description
Identify which database type will suit best for the necessities of this application. We will need to find a good hosted database for our developers to have the ability of sharing the same data, this will make it easier for spotting bugs and implementing new features.

# Things to keep in mind
* Our project is set up to use the ORM Prisma, we would need to be able to hook up the database to this ORM in order for us to use that particular database.
* By the looks of the app a structured database (SQL) would be an ideal candidate.
* The strongest hosting options for us are Railway and Vercel Strorage
* Vercel Storage is new and might be good checking it out
* Railway, has free tier and it refills every month
* Render, has free tier but only lasts 90 days 
* AWS RDS, good option too

**Comment by masiddee** [comment]
UPDATE: we are moving forward with Vercel Storage for hosting. Marking this as DONE
