### ISSUE TITLE
Database: clean up user auth data

### ISSUE THREAD

**Issue by Alesvoy** [masiddee/nextjs-soccer-manager#2]
# Description
- In order to implement certain business logic/permissions in our GraphQL queries and mutations, we need to map our Auth0 users to our Prisma users

# To Do:
- [x] Add `externalUserId` field to User model
- [x] Update Auth0 Login flow to pass entire User object in hook call, and map to Prisma user via `externalUserId` field
- [x] Update GraphQL resolver context to find the Prisma user, and pass this user into the resolver context

**Comment by masiddee** [comment]
This has been resolved. Closing
